### ISSUE TITLE
samepid feature doesn't work as expected

### ISSUE THREAD

**Issue by rasup** [trbs/pid#15]
script.py:
```python
pidfile = PidFile(allow_samepid=True)
pidfile.create()
while True:
   time.sleep(1)
```
If I start this script twice I would expect the second `create()` to raise a `PidFileError` but it doesn't.

I'm using version 2.1.1

**Comment by trbs** [comment]
Could you please create a PR with a test for this in our test suite ?

Thanks !

**Comment by trbs** [comment]
Thanks a lot for the PR and fix !
