### ISSUE TITLE
atexit registration is never done

### ISSUE THREAD

**Issue by rasup** [trbs/pid#24]
The registration is done [here](https://github.com/trbs/pid/blob/master/pid/__init__.py#L192) but since `self._is_setup` is always `True` it is never called (`setup()` is called as the first step in `create()`).

**Comment by trbs** [comment]
Please check the patch, also included a test to make sure we can spot regressions in the future.

**Comment by rasup** [comment]
Looks good. Thanks!

**Comment by trbs** [comment]
FYI Released v2.2.4 to pypi :-) https://pypi.org/project/pid/
